### ISSUE TITLE
Any plans tu update the gem to support  google-api-client 0.9 ?

### ISSUE THREAD

**Issue by adbeelitamar** [edap/yourub#10]
Or at least https://github.com/adbeelitamar/yourub/commit/f3a9a1a2ceb84f5ee37daed607d5bc435acf8559

**Comment by edap** [comment]
Yes, I will do it in the following month. I would love a PR too ;)

**Comment by edap** [comment]
@adbeelitamar for now, i've just disallowed the use of the version 0.9
