### ISSUE TITLE
raising exception in case of errors

### ISSUE THREAD

**Issue by kirillplatonov** [edap/yourub#11]
@edap Hello. First of all, this library is a great work. Thank you for sharing it!

Why you put error in log but not raising a relevant exception? I think with exception it's easier to be informed that something went wrong and handle it or fix reason of exception.

**Comment by edap** [comment]
Sorry for the late answer. Which part of the code are you referring to? I do not raise exceptions if something that I can foresee happen. Network failures or empty values are things that happen.
