### ISSUE TITLE
NoMethodError: undefined method `developer_key' for nil:NilClass

### ISSUE THREAD

**Issue by crestcode** [edap/yourub#4]
Installed latest version (v1.1.1) and created yourub.yml config file as indicated. When attempting to create a new client, I received this error:  

NoMethodError: undefined method `developer_key' for nil:NilClass

I went back and installed v1.0.5 and can confirm that everything works as it should.

**Comment by edap** [comment]
Hello @crestcode, sorry for the late answer. Please check the current version 2.0.0, in the readme file is explained how to initialize the client

**Comment by maxwolff** [comment]
I have the same problem, havent been able to figure it out. What did you want us to modify with the new readme? I replaced 

 @client ||= Yourub::Client.new

with

client = Yourub::Client.new
client.search(country: "DE", category: "sports", order: 'date') do |v|
  puts v
end

in my videos controller. is this what you meant?

**Comment by edap** [comment]
Which version of the gem are you using?
How are you passing the developer key?
You can try from the ruby console:

```ruby
options = { developer_key: 'mySecretKey'}
client = Yourub::Client.new(options)
```

**Comment by edap** [comment]
@maxwolff if ti works, i will close the issue

**Comment by maxwolff** [comment]
I'm busy today, but I will get to it. Can you leave the issue open, or
respond to my message in a few days?

On Tue, Feb 24, 2015 at 1:26 PM, Davide Prati <notifications@github.com>
wrote:

> @maxwolff <https://github.com/maxwolff> if ti works, i will close the
> issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edap/yourub/issues/4#issuecomment-75849547>.
>



-- 
Max Wolff
B.A. Candidate | Economics
Stanford University | Class of 2016

**Comment by edap** [comment]
@maxwolff  sure ;)

**Comment by edap** [comment]
hey @maxwolff, did you had time to testo it? if it works, i will close the issue

**Comment by edap** [comment]
ok @maxwolff , issue closed
