### ISSUE TITLE
When searching by ID, resulting hash is missing Description

### ISSUE THREAD

**Issue by crestcode** [edap/yourub#5]
When I search by ID:

client.search(id: "CmXIIL2tmR8")

The results seem incomplete when compared to the README example: 

[{"id"=>"CmXIIL2tmR8", "title"=>"Panda Bear - Mr Noah (Official Video)", "thumb"=>"https://i.ytimg.com/vi/CmXIIL2tmR8/default.jpg", "url"=>"https://www.youtube.com/watch?v=CmXIIL2tmR8"}] 

Specifically, the video's description is missing.

**Comment by edap** [comment]
hello @crestcode, thanks for your feedback. Actually the client is returning only some fields, to have all of them, you have to initialize the client, then:
```ruby
client.extended_info = true
client.search(id: "CmXIIL2tmR8")
```
a new version of the client is under rewriting(i will publish it at the end of the month), and returning all the fields will be the default.
